title: "Terminal.Fi XP Bot Manual"
description: "Telegram XP Bot Documentation"
remote_theme: just-the-docs/just-the-docs

# GitHub Pages 환경 변수
url: "https://koonnft.github.io"
baseurl: "/terminalfi-bot-manual"

# Navigation
nav_enabled: true

# Custom color scheme
color_scheme: terminalfi

# Aux links
aux_links:
  "GitHub Repo":
    - "https://github.com/KoonNFT/terminalfi-bot-manual"

# Search
search_enabled: true
search:
  button: true

# Plugins (GitHub Pages가 지원하는 공식 플러그인만!)
plugins:
  - jekyll-remote-theme
